### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by rdhrkns** [AnataCreative/gitPlugins#1]
There are two typo's in the path/filename of the function getBodyHtml

> gitPlugins/GitPluginsWidget

Corrected to the following:
    public function getBodyHtml()
    {
        return craft()->templates->render('gitplugins/gitPluginsWidget');
    }

makes it installable as a Widget, however the messages is: "You don't have permission to access this plugin.", despite being logged in as Adminsitrator

**Comment by IbeVanmeenen** [comment]
Hi, thanks for the feedback. I'll take a look at it as soon as I can! (abroad at the moment)

**Comment by IbeVanmeenen** [comment]
@rdhrkns , Fixed both issues and made a new release (v0.1.1). Thanks for spotting the bugs! Permission issue was due to personal and client version not having user management (I was working on pro version, witch has user management).
