### ISSUE TITLE
CP dashboard error

### ISSUE THREAD

**Issue by dowadidi** [AnataCreative/gitPlugins#9]
**Internal Server Error**
Unable to find the template “gitplugins/gitPluginsWidget”.

Craft PRO version 2.6.2791 (latest at the moment), running on a Apache server using PHP version 7.0.6

**Comment by Boggimedes** [comment]
I resolved this by renaming the template from "**G**itPluginsWidget" to "**g**etPluginsWidget", but when I submit a github plugin I get a blank page (and dev tools shows a 500 error in response to the post)

**Comment by phaetons** [comment]
The template name must start with upper case letter.

So change /widgets/GitPlugins_GitWidget, line 12 from:
`return craft()->templates->render('gitplugins/gitPluginsWidget');`
to 
`return craft()->templates->render('gitplugins/GitPluginsWidget');`

**Comment by IbeVanmeenen** [comment]
Hi, 

Thanks for the help and sorry it took so long to fix this (was a bit tied up).
I've pushed a fix to master. It was indeed a casesensitivity issue...

**Comment by Boggimedes** [comment]
Ignore me.  I was loading in PROD, but testing in DEV....
